### ISSUE TITLE
More guides

### ISSUE THREAD

**Issue by AashinShazar** [jefflgaol/Install-Packages-Jetson-ARM-Family#3]
Hey, I love the guide you have here on installing important packages and libraries on the Jetson. It's a huge life saver and informative guide. 

I was hoping I could request a guide or some sort of tutorial on how to install [Ray ](https://github.com/ray-project/ray) and [JAX ](https://github.com/google/jax) on the Jetson. They're pretty powerful libraries and I think a lot of people could benefit from a guide on how to install them on the Jetson ARM family devices (I'm having trouble myself haha).

Thanks again, much appreciated!

**Comment by jefflgaol** [comment]
Hi, AashinShazar! Thank you for your appreciation regarding this tutorial. Unfortunately, due to financial and interest issues, I could no longer work with Jetson in the near future. But, hopefully, I could get in touch with Jetson again, because I love working with AI and data science. :)

Thank you very much!

Though you may try this one
JAX: https://jax.readthedocs.io/en/latest/developer.html
